format = """
$os\
$sudo\
$custom\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$golang\
\n$character\
"""

# right_format = """
# $cmd_duration\
# $time\
# """

[os]
disabled = false
format = """
[](fg:#89b4fa)\
[$symbol]($style)\
[](fg:#89b4fa)\
"""
style = "fg:#313244 bg:#89b4fa"

[os.symbols]
Macos = "  "
Linux = " 󰌽 "
Ubuntu = "  "
Debian = "  "

[sudo]
disabled = false
symbol = ' 󰿆 sudo'
format = """
[](fg:#eba0ac)\
[$symbol]($style)\
[](fg:#eba0ac)\
"""
style = "bold fg:#313244 bg:#eba0ac "

[directory]
truncation_length = 5
truncation_symbol = ' '
truncate_to_repo = true
home_symbol = '󰋞 ~'
read_only = ' 󰌾 '
format = """
[](fg:#b4befe)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#b4befe)\
"""
style = 'bold fg:#313244 bg:#b4befe'
read_only_style = 'bold fg:#313244 bg:#b4befe'

[git_branch]
symbol = '  '
truncation_length = 10
truncation_symbol = ''
style = 'bold fg:#89dceb bg:#45475a'
format = """
[](fg:#45475a)\
[$symbol$branch(:$remote_branch)]($style)\
"""

[git_status]
disabled = false
style = 'bold fg:#eba0ac bg:#45475a'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = """
[  ](fg:#89dceb bg:#45475a)\
[$all_status$ahead_behind]($style)\
"""

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = 'bold fg:#a6e3a1 bg:#45475a'
deleted_style = 'bold fg:#89b4fa  bg:#45475a'
format = """
[  ](fg:#89dceb bg:#45475a)\
[+$added]($added_style)[-$deleted]($deleted_style)[](fg:#45475a)\
"""

[fill]
symbol = '─'
style = 'fg:#89b4fa) bg:none'

[golang]
symbol = "\U000f07d3 " # nf-md-language_go
# symbol = " " # nf-seti-go
format = '[$symbol($version )($mod_version )]($style)'

[python]
pyenv_version_name = false
symbol = '[ ](fg:#f9e2af bg:#8093fd)'
format = '[](fg:#8093fd)[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)[](fg:#8093fd)'
style = 'bold fg:#313244 bg:#8093fd'

[character]
success_symbol = '[❯](bold #9ece6a)'
error_symbol = '[❯](bold red)'

[cmd_duration]
show_milliseconds = true
min_time = 100
format = '[󰞌 $duration  ](fg:#f9e2af)'

[time]
disabled = false
format = '[ $time](bold fg:#6c7086)'
time_format = '%T'
